mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views
import portal

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^portal/', include('portal.urls')),
    url(r'^signup/', views.signup),
    url(r'^login/', views.login_view),
    url(r'^logout/', views.logout_route, name="logout"),
    url(r'^$', portal.views.index,name= 'index'),
]

portal/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<username>\w+)$', views.view_profile, name='get-user-info'),
    # url(r'^(?P<username>\w+)/social$', views.view_social, name='get-user-social'),
    # url(r'^(?P<username>\w+)/personal$', views.view_personal, name='get-user-personal'),
    # url(r'^$', views.index,name= 'index'),
    url(r'^demo$', views.demo,name= 'demo'),
    url(r'^location/enter$', views.location,name= 'location'),

    url(r'^(?P<username>\w+)/permanent_address/edit$', views.update_permanent_address, name='edit-permanent-address'),
    url(r'^(?P<username>\w+)/current_address/edit$', views.update_current_address, name='edit-current-address'),


    url(r'^(?P<username>\w+)/basic/edit$', views.update_basic, name='edit-user-basic'),
    url(r'^(?P<username>\w+)/social/edit$', views.update_social, name='edit-user-social'),
    url(r'^(?P<username>\w+)/personal/edit$', views.update_personal, name='edit-user-personal'),

    url(r'^(?P<username>\w+)/work_experience/add$', views.add_work_experience, name='add-work-experience'),
    url(r'^(?P<username>\w+)/work_experience/delete/(?P<pk>\w+)', views.delete_work_experience, name='delete-work-experience'),

    url(r'^(?P<username>\w+)/qualification/add$', views.add_qualification, name='add-user-qualification'),
    url(r'^(?P<username>\w+)/qualification/delete/(?P<pk>\w+)', views.delete_qualification, name='delete-qualification'),

    url(r'^address/update/(?P<pk>\w+)$', views.update_address)
    # url(r'^(?P<username>\w+)/work_experience/edit', views.update_work_experience, name='edit-user-work-experience'),
]

portal/models.py
from os.path import splitext
from enum import Enum

from django.db import models
from django.contrib.auth.models import User


# some enums
class Choice(object):
    @classmethod
    def choices(cls):
        try:
            return tuple([(item.value, item.name)
                        for item in list(cls)])
        except TypeError:
            return None



class Gender(int, Choice, Enum):
    male = 0
    female = 1
    others = 2

    def __str__(self):
        return self.name.capitalize()

class BloodGroup(int, Choice, Enum):
    A = 0
    B = 1
    AB = 2
    O = 3

    def __str__(self):
        return self.name.capitalize()


class MaritalStatus(int, Choice, Enum):
    married = 0
    single = 1

    def __str__(self):
        return self.name.capitalize()


class AcademicProgram(int, Choice, Enum):
    undergraduate = 0
    postgraduate = 1
    doctoral = 2
    dual_degree = 3

    def __str__(self):
        return self.name.capitalize()


class Visibility(int, Choice, Enum):
    public = 0
    only_me = 1
    iiita = 2

    def __str__(self):
        return self.name.capitalize()


def get_default_scope(scope=Visibility.iiita, null=True):
    return models.SmallIntegerField(
        choices=Visibility.choices(),
        null=null,
        default=scope
    )


# Create your models here.

class Address(models.Model):
    address_line_1 = models.CharField(max_length=100, blank=True)
    address_line_2 = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=20)
    username = models.CharField(max_length=20)

    def __str__(self):
        return "{} | {}, {}, {}".format(
            self.username,
            self.address_line_1,
            self.city,
            self.country
        )


class UserProfile(models.Model):
    def handle_upload(instance, filename):
        return '{}/{}{}'.format('uploads', instance.user.username, splitext(filename)[1])

    # basic info
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True
    )

    name = models.CharField(max_length=100, null=False)
    date_of_birth = models.DateField(null=False)
    gender = models.SmallIntegerField(choices=Gender.choices(), null=False)
    blood_group = models.SmallIntegerField(choices=BloodGroup.choices(), null=True, blank=True)
    marital_status = models.SmallIntegerField(choices=MaritalStatus.choices(), null=True, blank=True)
    nationality = models.CharField(max_length=50, null=False, blank=True)
    photograph = models.ImageField(upload_to=handle_upload, null=True, blank=True)

    # email and phone
    email_1 = models.EmailField(null=False, unique=True)
    email_2 = models.EmailField(null=True, blank=True)
    phone_1 = models.CharField(max_length=20, null=True, blank=True)
    phone_2 = models.CharField(max_length=20, null=True, blank=True)

    # social links
    link_facebook = models.CharField(max_length=100, null=True, blank=True)
    link_twitter = models.CharField(max_length=100, null=True, blank=True)
    link_linkedin = models.CharField(max_length=100, null=True, blank=True)
    link_skype = models.CharField(max_length=100, null=True, blank=True)

    # social links scope
    scope_facebook = get_default_scope()
    scope_twitter = get_default_scope()
    scope_linkedin = get_default_scope()
    scope_skype = get_default_scope()

    # social link to be public
    link_github = models.CharField(max_length=100, null=True, blank=True)
    link_blog = models.CharField(max_length=200, null=True, blank=True)
    link_website = models.CharField(max_length=200, null=True, blank=True)

    # addresses
    permanent_address = models.ForeignKey(
        Address,
        on_delete=models.CASCADE,
        related_name='permanent_address',
        null=True,
        blank=True
    )
    current_address = models.ForeignKey(
        Address,
        on_delete=models.CASCADE,
        related_name='current_address',
        null=True,
        blank=True
    )

    # addresss scope
    scope_permanent_address = get_default_scope()
    scope_current_address = get_default_scope()

    def __str__(self):
        return "{}".format(self.name)


class Qualification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    program_code = models.SmallIntegerField(choices=AcademicProgram.choices(), null=True)
    institute_name = models.CharField(max_length=200)
    start_date = models.DateField()
    end_date = models.DateField()
    convocation_year = models.SmallIntegerField()


    @property
    def program(self):
        return AcademicProgram(self.program_code).name.capitalize()


class WorkExperience(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    employer = models.CharField(max_length=150)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    sector = models.CharField(max_length=50, null=True)
    designation = models.CharField(max_length=50)
    founder = models.BooleanField(default=False, blank=True)
    location = models.OneToOneField(
        Address,
        on_delete=models.CASCADE
    )

portal/views.py
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, reverse, render, get_object_or_404
from django.conf import settings
from django.forms.models import model_to_dict
import django.forms as forms

from . import models
from .models import UserProfile, Address, Qualification, WorkExperience

from .forms import User_SocialLinksForm, User_PersonalInfoForm, User_BasicInfoForm
from .forms import AddressForm, WorkExperienceForm, QualificationForm, WorkExperienceModelForm


def resolve_scope(request, username):
    allowed_scopes = [models.Visibility.public.value]
    if request.user.is_authenticated:
        allowed_scopes.append(models.Visibility.iiita.value)

    if request.user.username in ['admin', username]:
        allowed_scopes.append(models.Visibility.only_me.value)
    return allowed_scopes


# Create your views here.
def location(request):
    return render(request, 'location.html')

def index(request):
    return render(request, 'index.html')


def demo(request):
    return render(request, 'demo.html')


def view_profile(request, username):
    user = get_object_or_404(User, username=username)
    profile = UserProfile.objects.get(user=user)
    context = {
        key: getattr(profile, key, None)
        for key in User_BasicInfoForm.Meta.fields +\
                   User_SocialLinksForm.Meta.fields +\
                   User_PersonalInfoForm.Meta.fields
    }

    context['experiences'] = WorkExperience.objects.filter(user=user).all()
    context['qualifications'] = Qualification.objects.filter(user=user).all()

    context['gender'] = str(models.Gender(context['gender']))
    context['username'] = user.username
    context['permanent_address'] = profile.permanent_address
    context['current_address'] = profile.current_address
    context['view_types'] = ['basic']

    context['allowed_scopes'] = resolve_scope(request, username)
    return render(request, 'display_profile.html', context)


@login_required
def update_basic(request, username):
    if username != request.user.username:
        return HttpResponse('Unauthorized', status=401)
    context = {
        'username': request.user.username,
        'form': None,
        'submit_url': reverse(update_basic, args=[username])
    }
    try:
        profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        profile = None

    if request.method == 'GET':
        if profile is None:
            context['form'] = User_BasicInfoForm()
        else:
            context['form'] = User_BasicInfoForm(initial=model_to_dict(profile))
        return render(request, 'generic_edit.html', context)
    else:
        if profile is None:
            form = User_BasicInfoForm(request.POST)
        else:
            form = User_BasicInfoForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect(reverse(view_profile, args=[context.get('username')]))
        else:
            context['form'] = form
            return render(request, 'generic_edit.html', context)


@login_required
def update_social(request, username):
    if username != request.user.username:
        return HttpResponse('Unauthorized', status=401)
    context = {
        'username': request.user.username,
        'form': None,
        'submit_url': reverse(update_social, args=[username])
    }
    try:
        profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        profile = None
    if request.method == 'GET':
        if profile is None:
            context['form'] = User_SocialLinksForm()
        else:
            context['form'] = User_SocialLinksForm(initial=model_to_dict(profile))
        return render(request, 'generic_edit.html', context)
    else:
        form = User_SocialLinksForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect(reverse(view_profile, args=[context.get('username')]))
        else:
            context['form'] = form
            return render(request, 'generic_edit.html', context)


@login_required
def update_personal(request, username):
    if username != request.user.username:
        return HttpResponse('Unauthorized', status=401)
    context = {
        'username': request.user.username,
        'form': None,
        'submit_url': reverse(update_personal, args=[username])
    }
    try:
        profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        profile = None
    if request.method == 'GET':
        if profile is None:
            context['form'] = User_PersonalInfoForm()
        else:
            context['form'] = User_PersonalInfoForm(initial=model_to_dict(profile))
        return render(request, 'generic_edit.html', context)
    else:
        form = User_PersonalInfoForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect(reverse(view_profile, args=[context.get('username')]))
        else:
            context['form'] = form
            return render(request, 'generic_edit.html', context)


@login_required
def update_permanent_address(request, username):
    if username != request.user.username:
        return HttpResponse('Unauthorized', status=401)
    context = {
        'username': username,
        'form': None,
        'submit_url': reverse(update_permanent_address, args=[username])
    }
    profile = get_object_or_404(UserProfile, user=request.user)
    if request.method == 'POST':
        if profile.permanent_address is None:
            profile.permanent_address = Address.objects.create()
            profile.permanent_address.save()
            profile.save()
        form = AddressForm(request.POST, instance=profile.permanent_address)
        if form.is_valid():
            form.save()
            return redirect(view_profile, username=username)
        else:
            context['form'] = form
            return render(request, 'generic_edit.html', context)
    else:
        if profile.permanent_address is None:
            context['form'] = AddressForm()
        else:
            context['form'] = AddressForm(initial=model_to_dict(profile.permanent_address))
        return render(request, 'generic_edit.html', context)


@login_required
def update_current_address(request, username):
    if username != request.user.username:
        return HttpResponse('Unauthorized', status=401)
    context = {
        'username': username,
        'form': None,
        'submit_url': reverse(update_current_address, args=[username])
    }
    profile = get_object_or_404(UserProfile, user=request.user)
    if request.method == 'POST':
        if profile.current_address is None:
            profile.current_address = Address.objects.create()
            profile.current_address.save()
            profile.save()
        form = AddressForm(request.POST, instance=profile.current_address)
        if form.is_valid():
            form.save()
            return redirect(view_profile, username=username)
        else:
            context['form'] = form
            return render(request, 'generic_edit.html', context)
    else:
        if profile.current_address is None:
            context['form'] = AddressForm()
        else:
            context['form'] = AddressForm(initial=model_to_dict(profile.current_address))
        return render(request, 'generic_edit.html', context)



@login_required
def update_address(request, pk):
    try:
        address = Address.objects.get(pk=pk)
    except Address.DidNotFound:
        address = None
    else:
        if address.username != request.user.username:
            return HttpResponse('Unauthorized', status=401)

    context = {
        'form': None,
        'username': request.user.username,
        'submit_url': reverse(update_address, args=[pk])
    }

    if request.method == 'GET':
        if address is None:
            context['form'] = AddressForm()
        else:
            context['form'] = AddressForm(initial=model_to_dict(address))
        return render(request, 'generic_edit.html', context)
    else:
        form = None
        if address is None:
            form = AddressForm(request.POST)
        else:
            form = AddressForm(request.POST, instance=address)
        addr = form.save(commit=False)
        addr.username = request.user.username
        addr.save()
        return HttpResponse(addr.pk, status=200)


@login_required
def add_work_experience(request, username):
    if username != request.user.username:
        return HttpResponse('Unauthorized', status=401)

    context = {
        'username': username,
        'form': None,
        'submit_url': reverse(add_work_experience, args=[username])
    }
    if request.method == 'POST':
        form = WorkExperienceForm(request.POST)
        if form.is_valid():
            exp = WorkExperience(employer=request.POST.get('employer'),
                                 start_date=request.POST.get('start_date'),
                                 end_date=request.POST.get('end_date'),
                                 sector=request.POST.get('sector'),
                                 designation=request.POST.get('designation'),
                                 founder=True
                                 if request.POST.get('founder') is 'on' else False)
            exp.user = request.user
            exp.location = Address.objects.get(pk=request.POST.get('address_pk'))
            exp.save()
            return redirect(view_profile, username=username)
        else:
            context['form'] = form
            return render(request, 'generic_edit.html', context)
    else:
        context['form'] = WorkExperienceForm()
        return render(request, 'generic_edit.html', context)

portal/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>Alumni Portal</title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />


  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

  <!-- CSS Files -->
  <link href="{%static "css/bootstrap.min.css" %}" rel="stylesheet" />
  <link href="{%static "css/material-kit.min.css%3Fv=1.1.1.css" %}" rel="stylesheet"/>

  <!-- CSS Just for demo purpose, don't include it in your project -->
  <!-- <link href="assets/assets-for-demo/vertical-nav.css" rel="stylesheet" />
  <link href="assets/assets-for-demo/demo.css" rel="stylesheet" /> -->

</head>

<body>

  <nav class="navbar navbar-default" role="navigation-demo">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
          <span class="sr-only">Alumni Portal</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'index' %}">Alumni Portal</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navigation-example-2">
        <ul class="nav navbar-nav navbar-right">
          <!-- <li>
            <a href="#">
              Discover
            </a>
          </li>
          <li>
            <a href="index.html#pablo">
              Wishlist
            </a>
          </li> -->

          <li>
            <a href="{% url 'logout' %}" class="btn btn-rose btn-raised btn-round">
              logout
            </a>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-->
  </nav>



  <div>
    {% block body %} {% endblock %}
  </div>



  <style>
   .clearfix {
       min-height: 20px;
   }
  </style>
  <div class="clearfix">
  </div>
  
  <footer class="footer footer-white footer-big">
    <div class="container">

      <div class="content">
<!-- Follow Us -->

<!-- End of folow us -->
        <div class="row">
          <div class="col-md-6 col-lg-6">
            <h5 style="font-family: fantasy ">About Us</h5>
            <ul class="links-vertical">
              <li>
                <a href="#" style="font-family: ">
                 IIITA
               </a>
             </li>
             <li>
              <a href="#" >
               About Us
             </a>
           </li>
           <li>
            <a href="#">
              Presentation
            </a>
          </li>
          <li>
            <a href="#">
              Contact Us
            </a>
          </li>
        </ul>
      </div>
<!--       <div class="col-md-2">
        <h5 style="font-family: fantasy">Market</h5>
        <ul class="links-vertical">
          <li>
            <a href="#">
             Sales FAQ
           </a>
         </li>
         <li>
          <a href="#">
            How to Register
          </a>
        </li>
        <li>
          <a href="#">
           Sell Goods
         </a>
       </li>
       <li>
        <a href="#">
          Receive Payment
        </a>
      </li>
      <li>
        <a href="#">
          Transactions Issues
        </a>
      </li>
      <li>
        <a href="#">
          Affiliates Program
        </a>
      </li>
    </ul>
  </div> -->

  <div class="col-md-6 col-lg-6">
    <h5 style="font-family: fantasy">Contact Information</h5>
    <div class="social-feed">
      <div class="feed-line">
        
        <p>Indian Institute of Information Technology,<br>Allahabad, Uttar Pradesh, Pin-code: 211012</p>
      </div>
      <div class="feed-line">
        <i class="fa fa-phone"></i>
        <p>+91-532-292-2005</p>
      </div>
      <div class="feed-line">
        <i class="fa fa-envelope"></i>
        <p>students.gymkhana@iiita.ac.in</p>
      </div>
    </div>
  </div>

</div>
</div>

<hr />
<div class="row">
  <div class="col-md-12 col-lg-12" style="text-align : center">
    <!-- <h5>Follow Us</h5> -->
    <ul class="social-buttons">
      <li>
        <a href="#" class="btn btn-just-icon btn-simple btn-twitter">
          <i class="fa fa-twitter"></i>
        </a>
      </li>
      <li>
        <a href="#" class="btn btn-just-icon btn-simple btn-facebook">
          <i class="fa fa-facebook-square"></i>
        </a>
      </li>
      <li>
        <a href="#" class="btn btn-just-icon btn-simple btn-dribbble">
          <i class="fa fa-dribbble"></i>
        </a>
      </li>
      <li>
        <a href="#" class="btn btn-just-icon btn-simple btn-google">
          <i class="fa fa-google-plus"></i>
        </a>
      </li>
      <li>
        <a href="#" class="btn btn-just-icon btn-simple btn-instagram">
          <i class="fa fa-instagram"></i>
        </a>
      </li>
    </ul>

  </div>
</div>
<div class="copyright pull-center">
  Copyright &copy; <script>document.write(new Date().getFullYear())</script> Geekhaven All Rights Reserved.
</div>
</div>
</footer>
</body>
<script src="{%static "js/jquery.min.js" %}" type="text/javascript"></script>
<script src="{%static "js/bootstrap.min.js" %}" type="text/javascript"></script>
<script src="{%static "js/material.min.js" %}"></script>

<!--  Plugin for Date Time Picker and Full Calendar Plugin-->
<script src="{%static "js/moment.min.js" %}"></script>

<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{%static "js/nouislider.min.js" %}" type="text/javascript"></script>

<!--  Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
<script src="{%static "js/bootstrap-datetimepicker.js" %}" type="text/javascript"></script>

<!--  Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
<script src="{%static "js/bootstrap-selectpicker.js" %}" type="text/javascript"></script>

<!--  Plugin for Tags, full documentation here: http://xoxco.com/projects/code/tagsinput/  -->
<script src="{%static "js/bootstrap-tagsinput.js" %}"></script>

<!--  Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="{%static "js/jasny-bootstrap.min.js" %}"></script>

<!-- Plugin For Google Maps -->
<!-- <script  type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAFPQibxeDaLIUHsC6_KqDdFaUdhrbhZ3M"></script> -->

<script src="{%static "js/atv-img-animation.js" %}" type="text/javascript"></script>

<!-- Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
<script src="{%static "js/material-kit.min.js" %}" type="text/javascript"></script>


<!-- Google API Code -->
 <!-- <script src="{%static "js/jquery.min.js" %}"></script> -->
 <script src="{%static "js/bloodhound.js" %}"></script>
 <script src="{%static "js/typeahead.jquery.js" %}"></script>
 <script src="{%static "js/typeahead-addresspicker.js" %}"></script>
 <script>
  function displayResults(result, div) {
    console.log(result);
    $('#id_address_line_2').val(result.placeResult.name);
    html = ["Address: " + result.address()]
    html.push("Latitude: " + result.lat())
    html.push("Longitude: " + result.lng())
    html.push("Long names:")
    result.addressTypes().forEach(function(type) {
      html.push("  " + type + ": " + result.nameForType(type))
    })
    html.push("Short names:")
    result.addressTypes().forEach(function(type) {
      html.push("  " + type + ": " + result.nameForType(type, true))
    })
    html.push('Location selected');
    div.html( html.join('\n'));
  }

  $( function() {
    var addressPicker = new AddressPicker();
    $('input#id_address_line_1').typeahead(null, {
      displayKey: 'description',
      source: addressPicker.ttAdapter()
    });
    addressPicker.bindDefaultTypeaheadEvent($('input#id_address_line_1'))
    $(addressPicker).on('addresspicker:selected', function (event, result) { displayResults(result, $('#response1'))})
    $(addressPicker).on('addresspicker:predictions', function(event, result) {
      if (result && result.length > 0)
        $('input#id_address_line_1').removeClass("empty")
      else
        $('input#id_address_line_1').addClass("empty")
    })
  })

  $( function() {

    // instantiate the addressPicker suggestion engine (based on bloodhound)
    var addressPicker = new AddressPicker({map: {id: '#map'}, marker: {draggable: true, visible: true}, zoomForLocation: 18, reverseGeocoding: true});

    // instantiate the typeahead UI
    console.log("hello");
    $('input#id_address_line_2').typeahead(null, {
      displayKey: 'description',
      source: addressPicker.ttAdapter()
    });
    addressPicker.bindDefaultTypeaheadEvent($('input#id_address_line_2'))
    $(addressPicker).on('addresspicker:selected', function (event, result) {
      displayResults(result, $('#response2'))
      if (result.isReverseGeocoding()) {
        $('input#id_address_line_2').val(result.address());
        console.log(result.address());
      }
    });
  })

  </script>

  <!-- Google API script Ends -->

<!-- Fixed Sidebar Nav - JS For Demo Purpose, Don't Include it in your project -->
<!-- <script src="assets/assets-for-demo/modernizr.js" type="text/javascript"></script>
  <script src="assets/assets-for-demo/vertical-nav.js" type="text/javascript"></script> -->

  <script type="text/javascript">

    $(document).ready(function(){
      var slider = document.getElementById('sliderRegular');

      noUiSlider.create(slider, {
        start: 40,
        connect: [true,false],
        range: {
          min: 0,
          max: 100
        }
      });

      var slider2 = document.getElementById('sliderDouble');

      noUiSlider.create(slider2, {
        start: [ 20, 60 ],
        connect: true,
        range: {
          min:  0,
          max:  100
        }
      });



      materialKit.initFormExtendedDatetimepickers();

    });
  </script>

  </html>

portal/templates/experience.html
{% extends "base.html" %}

{% block body %}
<div class="container">
    <h2 class="title">Work Experiences</h2>
    {% for exp in experiences %}
    **
        <ul>
            <h4 class="title"><li> {{ exp.employer }}
            </li></h4>
            <h4 class="title"><li> {{ exp.start_date }}
            </li></h4>
            <h4 class="title"><li> {{ exp.end_date }}
            </li></h4>
            <h4 class="title"><li> {{ exp.sector }}
            </li></h4>
            <h4 class="title"><li> {{ exp.designation }}
            </li></h4>
            <h4 class="title"><li> {{ exp.founder }}
            </li></h4>
            <h4 class="title"><li> {{ exp.location }}
            </li></h4>
        </ul>

    {% endfor %}
</div>
{% endblock %}

portal/templates/generic_edit.html
{% extends "base.html" %}
<!-- {% load staticfiles %} -->
{% block body %}
<style>
    input[type=checkbox], input[type=radio]{
        width: 169px;
        margin: -33px 0 0;
    }
</style>

    {#        <div class="main-container" >#}
    <div class="container" style="background: white; max-width: 600px;">
        <div class="row">
            <div class="col-md-offset-1 col-md-10 col-lg-offset-1 col-lg-10">
                <form action="{{ submit_url }}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in form.visible_fields %}

                        <div class="form-group">
                            {{ field.errors }}
                            {{ field.label_tag }} {{ field }}
                        </div>

                    {% endfor %}

                    {% for field in form.hidden_fields %}
                        <div>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <center>
                        <button class="btn btn-primary" style="">Submit</button>
                    </center>
                </form>
            </div>
        </div>
    </div>
    {#        </div>#}


    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBVrSg4njrEoCofqhB-7w9RWv3wAr4uSb8&v=3.exp&sensor=false&libraries=places"></script>

{% endblock %}

portal/templates/nav.html
{% block navigation %}

<nav class="navbar navbar-default" role="navigation-demo">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
      <span class="sr-only">Alumni Portal</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html#pablo">Alumni Portal</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navigation-example-2">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="index.html#pablo">
            Discover
          </a>
        </li>
        <li>
          <a href="index.html#pablo">
            Wishlist
          </a>
        </li>

        <li>
          <a href="index.html#pablo" class="btn btn-rose btn-raised btn-round" data-toggle="dropdown">
            Register
          </a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-->
</nav>
{% endblock %}